### ISSUE TITLE
Segmentation fault (core dumped) diamond blastp

### ISSUE THREAD

**Issue by manjot-nagyal** [Arkadiy-Garber/SprayNPray#10]
Hello I am trying to use SprayNPray for metagenome bins using the following command in slurm job:

`spray-and-pray.py -g ./bins/1.fa -ref ./db/nr.gz.dmnd -out ./bins_1 -t 8 --meta`

And I get the following in my error report:

`sh: line 1: 94719 Segmentation fault      (core dumped) diamond blastp --db ./db/nr.gz.dmnd --query ./bins/1.fa-proteins.faa --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore stitle --out ./bins/1.fa.blast --max-target-seqs 100 --evalue 1E-15 --threads 126 --query-cover 50 --subject-cover 50 > /dev/null 2>&1`

Looking at the `./bins/1.fa-proteins.faa` file, I noticed that the header contains white spaces (`c_000000000007_1 # 209 # 1087 # 1 # ID=1_1;partial=00;start_type=ATG;etc...`). After removing them and re-running the above command I was able to get the following result:

`#CPU threads: 8
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: ./bins
#Target sequences to report alignments for: 100
Opening the database...  [0.034s]
Database: ./db/nr.gz.dmnd (type: Diamond database, sequences: 707028945, letters: 272881947790)
Block size = 2000000000
Total time = 0.138s
Reported 0 pairwise alignments, 0 HSPs.
0 queries aligned.`

Spot checking one sequence form the query protein fasta file, I was able to blast it and get many hits. I'm not sure why the white space character's are being introduced, is there an easy way to resolve? Or perhaps the issue is different from what I mentioned and hence I am not getting any alignments back...? Thank you!

**Comment by Arkadiy-Garber** [comment]
Hi Manjot,

Thanks for your interest in this software, and sorry you're having issues.

I believe this issues is caused by the `-ref ./db/nr.gz.dmnd` argument. It looks like the nr file was gzipped before a DIAMOND database was built. Could you please try decompressing that  file with `gzip -d nr.gz` and then trying to re-build the DIAMOND database with `diamond makedb --in nr -d nr.dmnd`. More info can be found here: [https://github.com/bbuchfink/diamond_docs/blob/master/Documentation.MD](https://github.com/bbuchfink/diamond_docs/blob/master/Documentation.MD).

Let me know if this issue persists after this.
Arkadiy

**Comment by manjot-nagyal** [comment]
Thank you for the quick response!

I decompressed the database and converted the rebuilt the database to be DIAMOND compatible. I am getting the same issue in my slurm error output file:

`sh: line 1: 32844 Segmentation fault      (core dumped) diamond blastp --db ./db/nr.dmnd --query ./bins/1.fa-proteins.faa --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore stitle --out ./bins/1.fa.blast --max-target-seqs 100 --evalue 1E-15 --threads 8 --query-cover 50 --subject-cover 50 > /dev/null 2>&1`

Looking at the `./bins/1.fa-proteins.faa` header, I still see the white-space characters again.

**Comment by Arkadiy-Garber** [comment]
Hi Manjot,

Could you please run the command without " > /dev/null 2>&1", just to see if there's any additional error messages that come up?

Thanks,
Arkadiy

**Comment by Arkadiy-Garber** [comment]
Hey Manjot,

Just wanted to check in on this and see if there's been any updates on your end of being able to run this.

Thanks,
Arkadiy

**Comment by manjot-nagyal** [comment]
Below is the output I was getting by running just the diamond blastp command. However, I was able to resolve this by downgrading diamond from version 2.1.9 to 2.1.8. The `spray-and-pray.py` also runs successfully. Thank you!

> #CPU threads: 8
> Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
> Temporary directory: ./bins
> #Target sequences to report alignments for: 100
> Opening the database...  [0.039s]
> Database: ./db/nr.dmnd (type: Diamond database, sequences: 707028945, letters: 272881947790)
> Block size = 2000000000
> Building query seed set...  [0.059s]
> Algorithm: Query-indexed
> Building query histograms...  [0.006s]
> Seeking in database...  [0s]
> Loading reference sequences...  [2.438s]
> Length sorting reference...  [1.583s]
> Initializing dictionary...  [0.005s]
> Initializing temporary storage...  [0.005s]
> Building reference histograms...  [3.477s]
> Allocating buffers...  [0s]
> Processing query block 1, reference block 1/137, shape 1/2.
> Building reference seed array...  [1.845s]
> Building query seed array...  [0.005s]
> Computing hash join...  [0.141s]
> Searching alignments...  [0.384s]
> Deallocating memory...  [0s]
> Processing query block 1, reference block 1/137, shape 2/2.
> Building reference seed array...  [1.823s]
> Building query seed array...  [0.005s]
> Computing hash join...  [0.133s]
> Searching alignments...  [0.374s]
> Deallocating memory...  [0s]
> Deallocating buffers...  [0.002s]
> Clearing query masking...  [0s]
> Opening temporary output file...  [0s]
> Computing alignments... Loading trace points...  [0.716s]
> Sorting trace points...  [0.02s]
> Computing alignments... Segmentation fault (core dumped)

**Comment by Arkadiy-Garber** [comment]
Great, glad to hear that the issue has been resolved - sounds like version incompatibility was the cause of this. I'll add a note to the software page to ensure that users that build their own DIAMOND databases are aware of which version of DIAMOND spraynpray currently uses.

Thanks,
Arkadiy
