### ISSUE TITLE
Additional dependencies

### ISSUE THREAD

**Issue by rmzelle** [Arkadiy-Garber/SprayNPray#2]
Hi, I was trying to get SprayNPray up and running. After a (manual) install of the listed conda packages:

https://github.com/Arkadiy-Garber/SprayNPray/blob/f24ba7721a10d81f87bf4ba0ec993ee198002a9f/setup.sh#L21

and running the script, I got errors indicating the following additional dependencies:

* python3, fixed with `conda install -c bioconda python`
* numpy, fixed with `conda install -c anaconda numpy`
* matplotlib, fixed with `conda install -c conda-forge matplotlib`
* scikit-learn (sklearn), fixed with `conda install -c anaconda scikit-learn`

**Comment by Arkadiy-Garber** [comment]
Hi Rintze,

Thanks for your interest in SprayNPray and for letting me know about those additional dependencies, I will add them to the setup script.

Let me know if you have any other questions or issues.

Cheers,
Arkadiy
