### ISSUE TITLE
depth option in addition to bam option

### ISSUE THREAD

**Issue by liamfriar** [Arkadiy-Garber/SprayNPray#8]
Hi, thanks for the great tool. I am running spraynpray on 11 bins generated by metabat2 from one metagenome assembly. I am looping through those bins and calling spray-and-pray.py on each. When I call the bam option to get depth info, this calls jgi_summarize_bam_contig_depths call from metabat2. It would be great to be able to input a depth file directly to save computational time. I already have a depth file generated by jgi_summarize_bam_contig_depths from when I generated my bins, so there is no need to recreate it 11 times. I didn't mess with the code because that jgi_summarize_bam_contig_depths call only takes a minute or two, but would be a nice feature!

**Comment by Arkadiy-Garber** [comment]
Hey Liam,

Thanks for the note, that is a great idea! I just implemented that change (or attempted to). So you should be able to input the depth file directly via the -depth flag. Feel free to try it out after a fresh git clone and let me know if there are any issues.

Thanks,
Arkadiy

**Comment by liamfriar** [comment]
I ran the updated spraynpray on one metagenome bin that I had previously run on spraynpray before you added the -depth flag and it generated an identical *-top100.csv file. (as determined using cmp in bash). So it seems to work!

Thanks!

**Comment by Arkadiy-Garber** [comment]
Awesome, thanks for checking on that and letting me know!
